### ISSUE TITLE
Mediawiki Setup

### ISSUE THREAD

**Issue by brianking** [OSLC/oslc-community#5]
Setup OSLC Community [Mediawiki](https://www.mediawiki.org) instance.

Preference to have them live on sub-domains:
wiki.open-services.net
discourse.open-services.net

2 Options:

1. Self-hosting
https://www.mediawiki.org/wiki/Manual:Installation_guide

2. Paid hosting

Things to consider:

1. Cost
2. Features + addons being offered
3. Install process
4. Path to upgrades + maintenance

**Comment by berezovskyi** [comment]
I had lots of spam problems with MediaWiki when I hosted it. Make sure to evaluate alternatives, eg http://wiki.minix3.org/doku.php

**Comment by berezovskyi** [comment]
Are we still planning to do this?

**Comment by brianking** [comment]
No, we are NOT planning on doing this anymore. Closing.

For more details, see https://github.com/OSLC/oslc-site-hugo/issues/146.
